TRUNCATE TABLE `gms_categories`;
ALTER TABLE `gms_categories` AUTO_INCREMENT = 1;
INSERT INTO `gms_categories` (`name`) VALUES ('Weapons');
INSERT INTO `gms_categories` (`name`) VALUES ('Armor');
INSERT INTO `gms_categories` (`name`) VALUES ('Nanos (General)');
INSERT INTO `gms_categories` (`name`) VALUES ('Nanos (Adventurer)');
INSERT INTO `gms_categories` (`name`) VALUES ('Nanos (Agent)');
INSERT INTO `gms_categories` (`name`) VALUES ('Nanos (Bureaucrat)');
INSERT INTO `gms_categories` (`name`) VALUES ('Nanos (Doctor)');
INSERT INTO `gms_categories` (`name`) VALUES ('Nanos (Enforcer)');
INSERT INTO `gms_categories` (`name`) VALUES ('Nanos (Engineer)');
INSERT INTO `gms_categories` (`name`) VALUES ('Nanos (Fixer)');
INSERT INTO `gms_categories` (`name`) VALUES ('Nanos (Keeper)');
INSERT INTO `gms_categories` (`name`) VALUES ('Nanos (Martial Artist)');
INSERT INTO `gms_categories` (`name`) VALUES ('Nanos (Meta-Physicist)');
INSERT INTO `gms_categories` (`name`) VALUES ('Nanos (Nano-Technician)');
INSERT INTO `gms_categories` (`name`) VALUES ('Nanos (Shade)');
INSERT INTO `gms_categories` (`name`) VALUES ('Nanos (Soldier)');
INSERT INTO `gms_categories` (`name`) VALUES ('Nanos (Trader)');
INSERT INTO `gms_categories` (`name`) VALUES ('Symbs (Artillery)');
INSERT INTO `gms_categories` (`name`) VALUES ('Symbs (Control)');
INSERT INTO `gms_categories` (`name`) VALUES ('Symbs (Extermination)');
INSERT INTO `gms_categories` (`name`) VALUES ('Symbs (Infantry)');
INSERT INTO `gms_categories` (`name`) VALUES ('Symbs (Support)');
INSERT INTO `gms_categories` (`name`) VALUES ('Spirits');
INSERT INTO `gms_categories` (`name`) VALUES ('Implants & Cluster');
INSERT INTO `gms_categories` (`name`) VALUES ('Utilities');
INSERT INTO `gms_categories` (`name`) VALUES ('Others');
